# Generated by Django 5.0.6 on 2024-07-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forgot_pass_token',
            field=models.CharField(default='default_token_value', max_length=100),
            preserve_default=False,
        ),
    ]
